/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cajachica.view;

import com.cajachica.pojos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author reynaldo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    //obejeto que contiene los datos del usuario logueado 
    public static Usuario userlogin;

    public Principal() 
    {
        initComponents();
        userlogin = vtnLogin.user;//recibiendo el objeto usuario  de la ventana de logueqo
        LabelUsuario.setText(userlogin.getNombre() + " " + userlogin.getApellido());
        labelCargo.setText(userlogin.getCargo());
        //verificando el rol del usuario logueado  ADMINISTRADOR=1 ASISTENTE=2

        if (userlogin.getTipoUsuario() == 2) {
            iniciarRolusuarioAsistente();
        }
    }

    //metodo que realiza el control de roles de ususario del sistema
    public void iniciarRolusuarioAsistente() {
        itemvtnRegProyecto.setEnabled(false);
        itemvtnRegUsuario.setEnabled(false);
        itemUsertoProyect.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneRound1 = new org.edisoncor.gui.tabbedPane.TabbedPaneRound();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        sysMDI = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        itemvtnRegUsuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemvtnRegProyecto = new javax.swing.JMenuItem();
        itemUsertoProyect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/images/logueado.png"))); // NOI18N

        LabelUsuario.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        LabelUsuario.setText("jLabel3");

        label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        label.setText("Cargo:");

        labelCargo.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        labelCargo.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(LabelUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCargo)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label)
                            .addComponent(labelCargo)))
                    .addComponent(jLabel2)
                    .addComponent(LabelUsuario))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sysMDI.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sysMDILayout = new javax.swing.GroupLayout(sysMDI);
        sysMDI.setLayout(sysMDILayout);
        sysMDILayout.setHorizontalGroup(
            sysMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sysMDILayout.createSequentialGroup()
                .addContainerGap(1806, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sysMDILayout.setVerticalGroup(
            sysMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysMDILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(916, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/file.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/usuarios.png"))); // NOI18N
        jMenu6.setText("Usuario");

        itemvtnRegUsuario.setText("Registrar usuario");
        itemvtnRegUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemvtnRegUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(itemvtnRegUsuario);

        jMenuBar1.add(jMenu6);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/proyecto.png"))); // NOI18N
        jMenu5.setText("Proyecto");

        itemvtnRegProyecto.setText("Registrar proyecto");
        itemvtnRegProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemvtnRegProyectoActionPerformed(evt);
            }
        });
        jMenu5.add(itemvtnRegProyecto);

        itemUsertoProyect.setText("Adicionar usuario a proyecto");
        itemUsertoProyect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsertoProyectActionPerformed(evt);
            }
        });
        jMenu5.add(itemUsertoProyect);
        jMenu5.add(jSeparator1);

        jMenuItem2.setText("Ingresar presupuesto ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/caja.png"))); // NOI18N
        jMenu7.setText("Registro caja");

        jMenuItem4.setText("Cargar factura");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/reportes.png"))); // NOI18N
        jMenu8.setText("Reportes");
        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/ajustes.png"))); // NOI18N
        jMenu9.setText("Ajustes");

        jMenuItem1.setText("Configuración");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuBar1.add(jMenu9);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/info.png"))); // NOI18N
        jMenu2.setText("Acerca de");

        jMenuItem3.setText("Información");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sysMDI)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sysMDI)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemvtnRegProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemvtnRegProyectoActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnProyecto.validaVentana;
        if (varValidacion == null) {

            vtnProyecto pro = new vtnProyecto();
            pro.setTitle("Registro de proyecto");
            pro.setResizable(false);//no es redimencionable
            pro.setMaximizable(false);//no se puede maximizar
            pro.setClosable(true);//si se puede cerra la ventana
            pro.setIconifiable(true);
            sysMDI.add(pro);
            pro.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana registro de proyecto ya esta activa\nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemvtnRegProyectoActionPerformed

    private void itemvtnRegUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemvtnRegUsuarioActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnUsuario.validaVentana;
        if (varValidacion == null) {

            vtnUsuario alm = new vtnUsuario();
            alm.setTitle("registro de usuario");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            sysMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana registro de usuario ya esta activa\nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemvtnRegUsuarioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnPresupuesto.validaVentana;
        if (varValidacion == null) {

            vtnPresupuesto pre = new vtnPresupuesto();
            pre.setTitle("Ingreso de presuouesto");
            pre.setResizable(false);//no es redimencionable
            pre.setMaximizable(false);//no se puede maximizar
            pre.setClosable(true);//si se puede cerra la ventana
            pre.setIconifiable(true);
            sysMDI.add(pre);
            pre.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana ingreso de presupuesto ya esta activa\nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itemUsertoProyectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsertoProyectActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnAddUser.validaVentana;
        if (varValidacion == null)
        {
            vtnAddUser pre = new vtnAddUser();
            pre.setTitle("Adición usuario a proyecto");
            pre.setResizable(false);//no es redimencionable
            pre.setMaximizable(false);//no se puede maximizar
            pre.setClosable(true);//si se puede cerra la ventana
            pre.setIconifiable(true);
            sysMDI.add(pre);
            pre.setVisible(true);
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "La ventana adicion de usuario ya esta activa\nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemUsertoProyectActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnParametros.validaVentana;
        if (varValidacion == null)
        {
            vtnParametros pre = new vtnParametros();
            pre.setTitle("Configuración de sistema");
            pre.setResizable(false);//no es redimencionable
            pre.setMaximizable(false);//no se puede maximizar
            pre.setClosable(true);//si se puede cerra la ventana
            pre.setIconifiable(true);
            sysMDI.add(pre);
            pre.setVisible(true);
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "La ventana configuración \nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       String varValidacion = vtnCargarFactura.validaVentana;
        if (varValidacion == null)
        {
            vtnCargarFactura pre = new vtnCargarFactura();
            pre.setTitle("Cargar factura");
            pre.setResizable(false);//no es redimencionable
            pre.setMaximizable(false);//no se puede maximizar
            pre.setClosable(true);//si se puede cerra la ventana
            pre.setIconifiable(true);
            sysMDI.add(pre);
            pre.setVisible(true);
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "La ventana cargar factura ya esta activa\nya esa activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JMenuItem itemUsertoProyect;
    private javax.swing.JMenuItem itemvtnRegProyecto;
    private javax.swing.JMenuItem itemvtnRegUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelCargo;
    public static javax.swing.JDesktopPane sysMDI;
    private org.edisoncor.gui.tabbedPane.TabbedPaneRound tabbedPaneRound1;
    // End of variables declaration//GEN-END:variables
}
