/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cajachica.view;

import com.cajachica.dao.CargarfacturaDao;
import com.cajachica.dao.MontosTotalesDao;
import com.cajachica.dao.MovimientosCajaDao;
import com.cajachica.dao.PresupuestoDao;
import com.cajachica.pojos.Factura;
import com.cajachica.pojos.MovimientosCaja;
import com.cajachica.pojos.Usuario;
import java.awt.Color;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.Calendar;

import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.Validaciones;

/**
 *
 * @author Reynaldo
 */
public class vtnCargarFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form vtnCargarFactura
     */
    public static String validaVentana;//variable que realiza la validacion de ventana abierta
    private static Usuario userLogin = null;//usuario recuperado desde la pantalla principal

    public static Usuario getUserLogin() {
        return userLogin;
    }

    public static void setUserLogin(Usuario aUserLogin) {
        userLogin = aUserLogin;
    }

    public vtnCargarFactura() {
        initComponents();
        validaVentana = "x";//insertando un valor a la variable que valida a la ventana
        /*Poniendo el JinternalFrame al centro de la ventana*/
        int a = Principal.sysMDI.getWidth() - this.getWidth();
        int b = Principal.sysMDI.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);

        //insertando la fecha actual en el calendario de carga
        Calendar c2 = new GregorianCalendar();
        txtFcarga.setCalendar(c2);
        //fin-- insercin fecha actual

        //Recuperando el Usuario Logueado
        userLogin = vtnLogin.user;
        //fin de la recuperacin del usuario logueado

    }

    //Metodo que realiza la carga de los combos de los proyectos 
    public void cargarComboByRolUsuario(int idUsuario) {
        try {
            PresupuestoDao pdao = new PresupuestoDao();
            ResultSet consulta = pdao.listarRegPresupuestoByRol(idUsuario);
            comboProyectos.addItem("Seleccione un proyecto");
            while (consulta.next()) {
                comboProyectos.addItem(consulta.getString("nombreProyecto"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los proyectos " + ex.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }

    //Metodo que realiza la carga de los combos de los proyectos 
    public void cargarCombo() {
        try {
            PresupuestoDao pdao = new PresupuestoDao();
            ResultSet consulta = pdao.listarProyectos();
            comboProyectos.addItem("Seleccione un proyecto");
            while (consulta.next()) {
                comboProyectos.addItem(consulta.getString("nombreProyecto"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los proyectos " + ex.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }

    //Metodo que realiza el limpiado de los campos de la ventana
    public void limpiarCampos() {
        comboProyectos.setSelectedIndex(0);
        FechaFac.setCalendar(null);
        txtNFactura.setText("0");
        txtMonto.setText("0.0");
        txtDesc.setText("");
        listaCajaChica.setSelectedIndex(0);
        listaTipoDoc.setSelectedIndex(0);
        labelMonto.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FechaFac = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFcarga = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtNFactura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        listaCajaChica = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtMonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelMonto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        listaTipoDoc = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboProyectos = new javax.swing.JComboBox<>();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(122, 171, 242));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("REGISTRAR FACTURA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/images/cargarF.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel3.setText("Fecha de factura:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel4.setText("Fecha de carga:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel5.setText("Numero de factura:");

        txtNFactura.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtNFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNFactura.setText("0");
        txtNFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNFacturaKeyTyped(evt);
            }
        });

        jLabel6.setText("Monto:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel7.setText("Egresos:");

        listaCajaChica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione opción", "Transporte", "Servicios basicos", "Otros gastos" }));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel8.setText("Descripción:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        txtMonto.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setText("0.0");
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel9.setText("PRESUPUESTO DISPINIBLE (BS.):");

        labelMonto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelMonto.setText("MONTO");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/guardar.png"))); // NOI18N
        jButton1.setText("Registrar factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/modificar.png"))); // NOI18N
        jButton3.setText("Limpiar campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel10.setText("Tipo documento:");

        listaTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione documento", "Vale de caja" }));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel11.setText("Seleccione Proyecto:");

        comboProyectos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProyectosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(listaCajaChica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FechaFac, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNFactura)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtFcarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(listaTipoDoc, 0, 203, Short.MAX_VALUE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(comboProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(labelMonto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(listaCajaChica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(listaTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFcarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.dispose();
        validaVentana = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtNFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNFacturaKeyTyped
        // TODO add your handling code here:
        Validaciones v = new Validaciones();
        v.validaNumeros(txtNFactura);
    }//GEN-LAST:event_txtNFacturaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboProyectosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProyectosItemStateChanged
        CargarfacturaDao facDao = new CargarfacturaDao();
        Double total = 0.0;
        try {
            int idProyecto = facDao.recuperarIdByNombreProyecto(comboProyectos.getSelectedItem().toString());
            total = Double.valueOf(facDao.recuperarMontoTotaByProyecto(idProyecto));
            // JOptionPane.showMessageDialog(null, "----"+total, null, JOptionPane.ERROR_MESSAGE);

            if (total > 0) {
//                if (total <= 20 && total >=21) 
//                {
//                    labelMonto.setText(total.toString());
//                    labelMonto.setForeground(Color.red);
//                } else if (total >= 50) {
//                    labelMonto.setText(total.toString());
//                    labelMonto.setForeground(Color.blue);
//                } else if (total >= 100) {
                labelMonto.setForeground(Color.BLUE);
                labelMonto.setText(total.toString());
                //               }
            } else {
                JOptionPane.showMessageDialog(null, "El proyecto seleccionado no tiene presupuesto asignado..!!", null, JOptionPane.ERROR_MESSAGE);
                labelMonto.setText("0");
            }
            //JOptionPane.showMessageDialog(null, "--->"+proyecto, null, JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(vtnCargarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboProyectosItemStateChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        //Instruciones para carga de datos de roles de usuario
        // tipo de usuario 1= ADMINITRADOR DE SISTEMA
        //                 2= USUARIO GENERAL
        int tipoUsuario = userLogin.getTipoUsuario();
        if (tipoUsuario == 2) {
            cargarComboByRolUsuario(userLogin.getIdUsuario());
            txtFcarga.setEnabled(false);
        } else {
            cargarCombo();
        }
        labelMonto.setText("0");
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Validacion de los campos de formulario
        if (comboProyectos.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un proyecto..!!", null, JOptionPane.ERROR_MESSAGE);
            comboProyectos.requestFocusInWindow();
            return;
        }
        //Campo fecha factura
        if (FechaFac.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione la fecha de factura..!!", null, JOptionPane.ERROR_MESSAGE);
            FechaFac.requestFocusInWindow();
            return;
        }
        //Ingrese numero de factura
        if (txtNFactura.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de factura", null, JOptionPane.ERROR_MESSAGE);
            txtNFactura.requestFocusInWindow();
            return;
        }
        //Ingrese numero si es vacio
        if (txtNFactura.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de factura", null, JOptionPane.ERROR_MESSAGE);
            txtNFactura.requestFocusInWindow();
            return;
        }

        //Campo monto vacio
        if (txtMonto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el monto de la factura..!!", null, JOptionPane.ERROR_MESSAGE);
            txtMonto.requestFocusInWindow();
            return;
        }
        //Campo monto factura
        if (txtMonto.getText().equals("0.0") || txtMonto.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "El monto de la factura no puede ser cero..!!", null, JOptionPane.ERROR_MESSAGE);
            txtMonto.requestFocusInWindow();
            return;
        }

        //Validacion de la lista lista tipo de documento
        if (listaCajaChica.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento de la lista EGRESOS", null, JOptionPane.ERROR_MESSAGE);
            listaCajaChica.requestFocusInWindow();
            return;
        }

        //Validacion de la lista de opciones de egreso
        if (listaTipoDoc.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento de la lista TIPO DE DOCUMENTO", null, JOptionPane.ERROR_MESSAGE);
            listaTipoDoc.requestFocusInWindow();
            return;
        }

        //Campo descripcion de la factura
        if (txtDesc.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el detalle de la factura..!!", null, JOptionPane.ERROR_MESSAGE);
            txtDesc.requestFocusInWindow();
            return;
        }
        try
        {
            //insercion a la base de datos
            CargarfacturaDao cDao = new CargarfacturaDao();
            int idProyecto = cDao.recuperarIdByNombreProyecto(comboProyectos.getSelectedItem().toString());
            //Setenado los datos a al objeto factura
            Factura factura = new Factura();
            factura.setNroFactura(Integer.parseInt(txtNFactura.getText()));//numero de factura
            factura.setTipoDoc(listaTipoDoc.getSelectedItem().toString());//tipo de docuemento
            factura.setDetalleFactura(txtDesc.getText());//detalle afctura
            factura.setMontoFactura(Float.valueOf(txtMonto.getText()));//monto factura
            factura.setFecha(FechaFac.getDate());//fecha de factura
            factura.setFechaCargaSistema(txtFcarga.getDate());//fecha de carga sistema
            factura.setIdProyecto(idProyecto);//id proyecto
            factura.setIdUsuario(userLogin.getIdUsuario());//id de usuario

            //inicio del registro de la factura y actualizacion de los montos totales 
            MontosTotalesDao mDao = new MontosTotalesDao();
            ResultSet consulta = mDao.recuperarMontoIngreso(idProyecto);//recuperado el total de los ingresos
            String montoI = null;
            int idMonto = 0;//monto total de ingresos
            if (consulta.next()) {
                montoI = consulta.getString(1);
                idMonto = consulta.getInt(2);
            }

            if (Double.parseDouble(montoI) > Double.parseDouble(txtMonto.getText())) 
            {
                if (cDao.cargarFactura(factura))
                {
                    double montoE = 0;
                    montoE = Double.parseDouble(montoI) - Double.parseDouble(txtMonto.getText());
                    mDao.updateIngresosTotales(String.valueOf(montoE), idProyecto, idMonto);

                    //registro del movimientos
                    MovimientosCajaDao movDao = new MovimientosCajaDao();
                    MovimientosCaja m= new MovimientosCaja();
                    m.setIngreso("0");
                    m.setEgreso(cDao.ultimoRegistroFactura());
                    m.setSaldo(String.valueOf(montoE));
                    m.setGlosa(txtDesc.getText());
                    m.setIdProyecto(idProyecto);
                    m.setNroDocumento(Integer.parseInt(txtNFactura.getText()));
                    m.setIdUsuario(userLogin.getIdUsuario());
                    movDao.registrarMontoEngreso(m);
                    //fin del registro del movimiento

                    JOptionPane.showMessageDialog(null, "Registro de factura exitoso", null, JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "No tiene sufifientes fondos para registrar la factura..!!", null, JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la inserción de los datos..!!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtMonto.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaFac;
    private javax.swing.JComboBox<String> comboProyectos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JComboBox<String> listaCajaChica;
    private javax.swing.JComboBox<String> listaTipoDoc;
    private javax.swing.JTextArea txtDesc;
    private com.toedter.calendar.JDateChooser txtFcarga;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNFactura;
    // End of variables declaration//GEN-END:variables
}
