/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cajachica.view;

import com.cajachica.core.Utilitarios;
import com.cajachica.core.Validaciones;
import com.cajachica.dao.UsuarioDao;
import com.cajachica.pojos.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reynaldo
 */
public class vtnUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form vtnUsuario
     */
    public static String validaVentana;//variable que realiza la validacion de ventana abierta
    public Usuario Objetousuario = new Usuario();

    public vtnUsuario() {
        initComponents();

        validaVentana = "x";//insertando un valor a la variable que valida a la ventana
        /*Poniendo el JinternalFrame al centro de la ventana*/
        int a = Principal.sysMDI.getWidth() - this.getWidth();
        int b = Principal.sysMDI.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);

        bloquearCamposFormulario();
        listarUsuarios();

    }

    //Metodo que bloquea los campos de texto
    public void bloquearCamposFormulario() {
        txtNomUsr.setEnabled(false);
        txtApeUsr.setEnabled(false);
        txtCargoUsr.setEnabled(false);
        txtCelUsr.setEnabled(false);
        txtEmailUsr.setEnabled(false);
        comboTUrs.setEnabled(false);
        comboTUrs.setEnabled(false);
        txtPassUsr.setEnabled(false);
        txtPassUsr2.setEnabled(false);
        btnAcepUser.setEnabled(false);
        btnCanUsr.setEnabled(false);
        // btnActivarOp.setEnabled(true);
        btnActualizarUsr.setEnabled(false);
        btnEliminiarUsr.setEnabled(false);
        //--------botones de accion-----
        btnHabilitar.setEnabled(true);
        btnHabilitar.setText("Habilitar Edición");

        //--------fin botones de accion---
    }

    public void limpiarCampos() {
        txtNomUsr.setText("");
        txtApeUsr.setText("");
        txtCargoUsr.setText("");
        txtCelUsr.setText("");
        txtEmailUsr.setText("");
        comboTUrs.setSelectedIndex(0);
        txtPassUsr.setText("");
        txtPassUsr2.setText("");

    }

    //Metodo que bloquea los campos de texto
    public void activarCamposFormulario() {
        txtNomUsr.setEnabled(true);
        txtApeUsr.setEnabled(true);
        txtCargoUsr.setEnabled(true);
        txtCelUsr.setEnabled(true);
        txtEmailUsr.setEnabled(true);
        comboTUrs.setEnabled(true);

        txtPassUsr.setEnabled(true);
        txtPassUsr2.setEnabled(true);
        btnAcepUser.setEnabled(true);
        btnCanUsr.setEnabled(true);
        // btnActivarOp.setEnabled(false);
        btnActualizarUsr.setEnabled(true);
        btnEliminiarUsr.setEnabled(true);
        btnNuevoUsr.setEnabled(false);
        //--------botones de accion-----
        // btnHabilitar.setEnabled(true);
        //btnHabilitar.setText("Habilitar Edición");

        //--------fin botones de accion---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomUsr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCargoUsr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailUsr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApeUsr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCelUsr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboTUrs = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPassUsr = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtPassUsr2 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnNuevoUsr = new javax.swing.JButton();
        btnAcepUser = new javax.swing.JButton();
        btnCanUsr = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnActualizarUsr = new javax.swing.JButton();
        btnEliminiarUsr = new javax.swing.JButton();
        btnHabilitar = new javax.swing.JToggleButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(122, 171, 242));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/images/usuario.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("REGISTRO DE USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addGap(13, 13, 13))
        );

        jLabel3.setText("Nombre:");

        jLabel5.setText("Cargo:");

        jLabel7.setText("Email:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailUsr))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCargoUsr))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCargoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Apellidos:");

        jLabel6.setText("Celular:");

        txtCelUsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelUsrKeyTyped(evt);
            }
        });

        jLabel8.setText("Tipo usuario:");

        comboTUrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Administrador", "Asistente" }));

        jLabel9.setText("Contraseña:");

        jLabel10.setText("Repita contraseña:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNuevoUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/agregar.png"))); // NOI18N
        btnNuevoUsr.setText("Nuevo");
        btnNuevoUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsrActionPerformed(evt);
            }
        });

        btnAcepUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/guardar.png"))); // NOI18N
        btnAcepUser.setText("Guardar");
        btnAcepUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepUserActionPerformed(evt);
            }
        });

        btnCanUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/cancelar.png"))); // NOI18N
        btnCanUsr.setText("Cancelar");
        btnCanUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnNuevoUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAcepUser)
                .addGap(18, 18, 18)
                .addComponent(btnCanUsr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAcepUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCanUsr))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Celular", "Cargo", "Email", "Tipo Usuario", "Contraseña"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaUsuariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnActualizarUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/modificar.png"))); // NOI18N
        btnActualizarUsr.setText("Actualizar");
        btnActualizarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsrActionPerformed(evt);
            }
        });

        btnEliminiarUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/delete.png"))); // NOI18N
        btnEliminiarUsr.setText("Eliminar");
        btnEliminiarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminiarUsrActionPerformed(evt);
            }
        });

        btnHabilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajachica/iconos/habilitar.png"))); // NOI18N
        btnHabilitar.setText("Habilitar opciones");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnHabilitar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarUsr)
                .addGap(28, 28, 28)
                .addComponent(btnEliminiarUsr)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarUsr)
                    .addComponent(btnEliminiarUsr)
                    .addComponent(btnHabilitar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApeUsr)
                            .addComponent(txtCelUsr)
                            .addComponent(comboTUrs, 0, 177, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtPassUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPassUsr2))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApeUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCelUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboTUrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPassUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPassUsr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        validaVentana = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnNuevoUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsrActionPerformed
        // TODO add your handling code here:
        activarCamposFormulario();
        limpiarCampos();
        btnHabilitar.setEnabled(false);
        btnActualizarUsr.setEnabled(false);
        btnEliminiarUsr.setEnabled(false);
    }//GEN-LAST:event_btnNuevoUsrActionPerformed

    private void btnCanUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanUsrActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        bloquearCamposFormulario();
        btnNuevoUsr.setEnabled(true);
        btnHabilitar.setEnabled(true);
    }//GEN-LAST:event_btnCanUsrActionPerformed

    private void btnAcepUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepUserActionPerformed
        // TODO add your handling code here:
        try {
            List<String> validar = new ArrayList<>();
            validar.add(txtNomUsr.getText());
            validar.add(txtApeUsr.getText());
            validar.add(txtCargoUsr.getText());
            validar.add(txtCelUsr.getText());
            validar.add(txtEmailUsr.getText());
            validar.add(txtPassUsr.getText());
            validar.add(txtPassUsr2.getText());

            if (new Validaciones().validarCampos(validar)) {
                if (comboTUrs.getSelectedIndex() != 0) {
                    if (txtPassUsr.getText().equals(txtPassUsr2.getText())) {

                        Usuario user = new Usuario(txtNomUsr.getText(), txtApeUsr.getText(), Integer.parseInt(txtCelUsr.getText()), txtCargoUsr.getText(), txtEmailUsr.getText(), txtPassUsr.getText(), comboTUrs.getSelectedIndex());
                        UsuarioDao userDao = new UsuarioDao();
                        if (userDao.registarUsuario(user)) {
                            JOptionPane.showMessageDialog(this, "Registro de usuario correcto..!!", null, JOptionPane.INFORMATION_MESSAGE);
                            limpiarCampos();
                            bloquearCamposFormulario();
                            listarUsuarios();
                            btnNuevoUsr.setEnabled(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Las contraseñas ingresadas no son iguales..!!", null, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione un elemento de la lista tipo de usuario..!!", null, JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Faltan campos por llenar..!!", null, JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception E) {
            JOptionPane.showMessageDialog(this, E.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAcepUserActionPerformed

    //Metodo que realiza el listado de los usuarios registrados
    public void listarUsuarios() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) this.tablaUsuarios.getModel();//creando el modela ára llenar los datos al JTableje
            Utilitarios util = new Utilitarios();
            util.limpiarTabla(tablaUsuarios);
            //realizando la consulta para realizar el listado de los datos
            UsuarioDao almDao = new UsuarioDao();
            List<Usuario> lista = almDao.listarUsuario();
            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < lista.size(); i++) {
                fila[0] = lista.get(i).getIdUsuario();
                fila[1] = lista.get(i).getNombre();
                fila[2] = lista.get(i).getApellido();
                fila[3] = lista.get(i).getCelular();
                fila[4] = lista.get(i).getCargo();
                fila[5] = lista.get(i).getEmail();
                if (lista.get(i).getTipoUsuario() == 1) {
                    fila[6] = "Administrador";
                } else {
                    fila[6] = "Asistente";
                }
                fila[7] = lista.get(i).getPassword();

                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e, null, JOptionPane.ERROR_MESSAGE);
        }
    }
    private void txtCelUsrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelUsrKeyTyped
        // TODO add your handling code here:
        new Validaciones().validaNumeros(txtCelUsr);
    }//GEN-LAST:event_txtCelUsrKeyTyped

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (btnHabilitar.isSelected()) {
            activarCamposFormulario();
            btnNuevoUsr.setEnabled(false);
            btnCanUsr.setEnabled(false);
            btnAcepUser.setEnabled(false);
            btnActualizarUsr.setEnabled(true);
            btnEliminiarUsr.setEnabled(true);
            btnHabilitar.setText("Cancelar");
        } else {
            limpiarCampos();
            bloquearCamposFormulario();
            btnHabilitar.setEnabled(true);
            tablaUsuarios.setEnabled(true);
            btnHabilitar.setText("Habilitar Edición");
            btnNuevoUsr.setEnabled(true);
        }
    }//GEN-LAST:event_btnHabilitarActionPerformed

    private void tablaUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMousePressed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) tablaUsuarios.getModel();
        String dato = String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 0));
        UsuarioDao userDao = new UsuarioDao();
        try {
            Usuario user = new Usuario();
            user.setIdUsuario(Integer.parseInt(dato));
            user.setNombre(String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 1)));
            user.setApellido(String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 2)));
            user.setCelular(Integer.parseInt(String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 3))));
            user.setCargo(String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 4)));
            user.setEmail(String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 5)));
            user.setPassword(String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 7)));

            String Tusuario = String.valueOf(tm.getValueAt(tablaUsuarios.getSelectedRow(), 6));
            //JOptionPane.showMessageDialog(null, Tusuario,null,JOptionPane.CANCEL_OPTION);
            if (Tusuario.equals("Administrador")) {
                user.setTipoUsuario(1);
            } else {
                user.setTipoUsuario(2);
            }

            this.setObjetoUsuario(user);//insertando el
            txtNomUsr.setText(user.getNombre());
            txtApeUsr.setText(user.getApellido());
            txtCargoUsr.setText(user.getCargo());
            txtCelUsr.setText(Integer.toString(user.getCelular()));
            txtEmailUsr.setText(user.getEmail());
            txtPassUsr.setText(user.getPassword());
            txtPassUsr2.setText(user.getPassword());
            comboTUrs.setSelectedIndex(user.getTipoUsuario());
            // comboTUrs.setSelectedIndex(user.getTipoUsuario());

            //JOptionPane.showMessageDialog(null, "Precionado" + cat.getNombre());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error" + ex.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tablaUsuariosMousePressed

    private void btnActualizarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsrActionPerformed
        try {
            List<String> validar = new ArrayList<>();
            validar.add(txtNomUsr.getText());
            validar.add(txtApeUsr.getText());
            validar.add(txtCargoUsr.getText());
            validar.add(txtCelUsr.getText());
            validar.add(txtEmailUsr.getText());
            validar.add(txtPassUsr.getText());
            validar.add(txtPassUsr2.getText());

            if (new Validaciones().validarCampos(validar)) {
                if (comboTUrs.getSelectedIndex() != 0) {
                    if (txtPassUsr.getText().equals(txtPassUsr2.getText())) {

                        Usuario user = new Usuario(this.getObjetoUsuario().getIdUsuario(), txtNomUsr.getText(), txtApeUsr.getText(), Integer.parseInt(txtCelUsr.getText()), txtCargoUsr.getText(), txtEmailUsr.getText(), txtPassUsr.getText(), comboTUrs.getSelectedIndex());
                        UsuarioDao userDao = new UsuarioDao();
                        if (userDao.actualizarUsuario(user)) {
                            JOptionPane.showMessageDialog(this, "Actualización de usuario correcto..!!", null, JOptionPane.INFORMATION_MESSAGE);
                            limpiarCampos();
                            bloquearCamposFormulario();
                            listarUsuarios();
                            btnNuevoUsr.setEnabled(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Las contraseñas ingresadas no son iguales..!!", null, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione un elemento de la lista tipo de usuario..!!", null, JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Faltan campos por llenar..!!", null, JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception E) {
            JOptionPane.showMessageDialog(this, E.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarUsrActionPerformed

    private void btnEliminiarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminiarUsrActionPerformed
        // TODO add your handling code here:
        try {
            if (!txtNomUsr.getText().equals("")) {
                int y = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el registro?");
                if (y == JOptionPane.YES_OPTION) 
                {
                    UsuarioDao userDao = new UsuarioDao();
                    if (userDao.eliminarUsuario(this.getObjetoUsuario())) 
                    {
                        JOptionPane.showMessageDialog(this, "Eliminacion correcta", "Mensaje..!!", JOptionPane.INFORMATION_MESSAGE);
                        limpiarCampos();
                        bloquearCamposFormulario();
                        listarUsuarios();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un Usuario a eliminar..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Hay proyectos asociados a este usuario..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminiarUsrActionPerformed

    public void setObjetoUsuario(Usuario user) {
        this.Objetousuario = user;
    }

    public Usuario getObjetoUsuario() {
        return this.Objetousuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcepUser;
    private javax.swing.JButton btnActualizarUsr;
    private javax.swing.JButton btnCanUsr;
    private javax.swing.JButton btnEliminiarUsr;
    private javax.swing.JToggleButton btnHabilitar;
    private javax.swing.JButton btnNuevoUsr;
    private javax.swing.JComboBox<String> comboTUrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtApeUsr;
    private javax.swing.JTextField txtCargoUsr;
    private javax.swing.JTextField txtCelUsr;
    private javax.swing.JTextField txtEmailUsr;
    private javax.swing.JTextField txtNomUsr;
    private javax.swing.JPasswordField txtPassUsr;
    private javax.swing.JPasswordField txtPassUsr2;
    // End of variables declaration//GEN-END:variables
}
