package com.cajachica.pojos;
// Generated Feb 3, 2019 10:43:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private int nroFactura;
     private String tipoDoc;
     private String detalleFactura;
     private float montoFactura;
     private Date fecha;
     private Date fechaCargaSistema;
     private int idProyecto;
     private int idUsuario;

    public Factura() 
    {
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Factura(int nroFactura, String tipoDoc, String detalleFactura, float montoFactura, Date fecha, Date fechaCargaSistema) {
       this.nroFactura = nroFactura;
       this.tipoDoc = tipoDoc;
       this.detalleFactura = detalleFactura;
       this.montoFactura = montoFactura;
       this.fecha = fecha;
       this.fechaCargaSistema = fechaCargaSistema;
    }

    public int getIdProyecto() {
        return idProyecto;
    }

    public void setIdProyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public String getDetalleFactura() {
        return this.detalleFactura;
    }
    
    public void setDetalleFactura(String detalleFactura) {
        this.detalleFactura = detalleFactura;
    }
    public float getMontoFactura() {
        return this.montoFactura;
    }
    
    public void setMontoFactura(float montoFactura) {
        this.montoFactura = montoFactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaCargaSistema() {
        return this.fechaCargaSistema;
    }
    
    public void setFechaCargaSistema(Date fechaCargaSistema) {
        this.fechaCargaSistema = fechaCargaSistema;
    }




}


