package com.cajachica.pojos;
// Generated Feb 3, 2019 10:43:40 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

    private Integer idProyecto;
    private String nombreProyecto;
    private String descripcion;
    private List<Usuario> usuarios = new ArrayList<>();// Objeto que mantiene la relacion de muchos a muchos entre la talbla proyecto y usuarios

    public Proyecto() {
    }

    public Proyecto(Integer idProyecto, String nombreProyecto, String descripcion) {
        this.idProyecto = idProyecto;
        this.nombreProyecto = nombreProyecto;
        this.descripcion = descripcion;
    }

    public Proyecto(String nombreProyecto, String descripcion) {
        this.nombreProyecto = nombreProyecto;
        this.descripcion = descripcion;
    }

    public Integer getIdProyecto() {
        return this.idProyecto;
    }

    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }

    public String getNombreProyecto() {
        return this.nombreProyecto;
    }

    public void setNombreProyecto(String nombreProyecto) {
        this.nombreProyecto = nombreProyecto;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public List<Usuario> getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
}
