package com.cajachica.pojos;
// Generated Feb 3, 2019 10:43:40 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;


/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int idUsuario;
    private String nombre;
    private String apellido;
    private int celular;
    private String cargo;
    private String email;
    private String password;
    private int tipoUsuario; // 
//----------------------------------
   private List<Proyecto> proyectos=new ArrayList<>();//objeto que mantiene la relacion con la tabla Proyecto (N:M)

    public Usuario() {
        
    }

    public Usuario(String nombre, String apellido, int celular, String cargo, String email, String password, int tipoUsuario) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.celular = celular;
        this.cargo = cargo;
        this.email = email;
        this.password = password;
        this.tipoUsuario = tipoUsuario;
    }

    public Usuario(int idUsuario, String nombre, String apellido, int celular, String cargo, String email, String password, int tipoUsuario) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.celular = celular;
        this.cargo = cargo;
        this.email = email;
        this.password = password;
        this.tipoUsuario = tipoUsuario;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public int getCelular() {
        return this.celular;
    }

    public void setCelular(int celular) {
        this.celular = celular;
    }

    public String getCargo() {
        return this.cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getTipoUsuario() {
        return this.tipoUsuario;
    }

    public void setTipoUsuario(int tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public List<Proyecto> getProyectos() {
        return proyectos;
    }

    public void setProyectos(List<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }
}
